# Generated by Django 3.1.5 on 2021-02-01 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20210201_2339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
